In [1]:
from pathlib import Path

import numpy as np
from stl import mesh

from mpl_toolkits import mplot3d
from matplotlib import pyplot as plt
%matplotlib widget

dtype([('normals', '<f4', (3,)), ('vectors', '<f4', (3, 3)), ('attr', '<u2', (1,))])

In [2]:
stl_file = Path('.').resolve().parent / 'example-pyramid.stl'
stl_file

PosixPath('/Users/nordin/Documents/Projects/3D_printer_slicers/OpenGL-STL-slicer/example-pyramid.stl')

In [3]:
example_mesh = mesh.Mesh.from_file(stl_file)
example_mesh

In [4]:
len(example_mesh.points)

20

In [5]:
example_mesh.points

array([[3.0e+00, 2.0e+00, 5.0e+00, 5.0e+00, 3.0e+00, 5.0e+00, 3.0e+00,
        3.0e+00, 5.0e+00],
       [0.0e+00, 1.0e+01, 0.0e+00, 0.0e+00, 1.0e+01, 1.0e-02, 1.5e+01,
        1.0e+01, 0.0e+00],
       [1.5e+01, 0.0e+00, 0.0e+00, 1.5e+01, 1.0e+01, 0.0e+00, 1.5e+01,
        0.0e+00, 1.0e-02],
       [1.5e+01, 0.0e+00, 1.0e-02, 5.0e+00, 2.0e+00, 5.0e+00, 0.0e+00,
        0.0e+00, 1.0e-02],
       [1.5e+01, 1.0e+01, 0.0e+00, 0.0e+00, 1.0e+01, 1.0e-02, 1.5e+01,
        1.0e+01, 1.0e-02],
       [5.0e+00, 3.0e+00, 5.0e+00, 0.0e+00, 1.0e+01, 1.0e-02, 3.0e+00,
        3.0e+00, 5.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 1.5e+01, 1.0e+01, 0.0e+00, 1.5e+01,
        0.0e+00, 0.0e+00],
       [0.0e+00, 1.0e+01, 0.0e+00, 1.5e+01, 1.0e+01, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [1.5e+01, 1.0e+01, 1.0e-02, 5.0e+00, 3.0e+00, 5.0e+00, 1.5e+01,
        0.0e+00, 1.0e-02],
       [0.0e+00, 0.0e+00, 1.0e-02, 5.0e+00, 2.0e+00, 5.0e+00, 3.0e+00,
        2.0e+00, 5.0e+00],
       [3.0e+00, 2.0

In [6]:
example_mesh.points[0]

array([3., 2., 5., 5., 3., 5., 3., 3., 5.], dtype=float32)

In [10]:
len(example_mesh.vectors)

20

In [9]:
example_mesh.vectors

array([[[3.0e+00, 2.0e+00, 5.0e+00],
        [5.0e+00, 3.0e+00, 5.0e+00],
        [3.0e+00, 3.0e+00, 5.0e+00]],

       [[0.0e+00, 1.0e+01, 0.0e+00],
        [0.0e+00, 1.0e+01, 1.0e-02],
        [1.5e+01, 1.0e+01, 0.0e+00]],

       [[1.5e+01, 0.0e+00, 0.0e+00],
        [1.5e+01, 1.0e+01, 0.0e+00],
        [1.5e+01, 0.0e+00, 1.0e-02]],

       [[1.5e+01, 0.0e+00, 1.0e-02],
        [5.0e+00, 2.0e+00, 5.0e+00],
        [0.0e+00, 0.0e+00, 1.0e-02]],

       [[1.5e+01, 1.0e+01, 0.0e+00],
        [0.0e+00, 1.0e+01, 1.0e-02],
        [1.5e+01, 1.0e+01, 1.0e-02]],

       [[5.0e+00, 3.0e+00, 5.0e+00],
        [0.0e+00, 1.0e+01, 1.0e-02],
        [3.0e+00, 3.0e+00, 5.0e+00]],

       [[0.0e+00, 0.0e+00, 0.0e+00],
        [1.5e+01, 1.0e+01, 0.0e+00],
        [1.5e+01, 0.0e+00, 0.0e+00]],

       [[0.0e+00, 1.0e+01, 0.0e+00],
        [1.5e+01, 1.0e+01, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00]],

       [[1.5e+01, 1.0e+01, 1.0e-02],
        [5.0e+00, 3.0e+00, 5.0e+00],
        [1.5e+01, 0.0e

In [7]:
example_mesh.vectors[0]

array([[3., 2., 5.],
       [5., 3., 5.],
       [3., 3., 5.]], dtype=float32)

In [8]:
example_mesh.vectors[0][1]

array([5., 3., 5.], dtype=float32)

In [14]:
example_mesh.v0

array([[3.0e+00, 2.0e+00, 5.0e+00],
       [0.0e+00, 1.0e+01, 0.0e+00],
       [1.5e+01, 0.0e+00, 0.0e+00],
       [1.5e+01, 0.0e+00, 1.0e-02],
       [1.5e+01, 1.0e+01, 0.0e+00],
       [5.0e+00, 3.0e+00, 5.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 1.0e+01, 0.0e+00],
       [1.5e+01, 1.0e+01, 1.0e-02],
       [0.0e+00, 0.0e+00, 1.0e-02],
       [3.0e+00, 2.0e+00, 5.0e+00],
       [3.0e+00, 3.0e+00, 5.0e+00],
       [1.5e+01, 0.0e+00, 1.0e-02],
       [0.0e+00, 0.0e+00, 1.0e-02],
       [1.5e+01, 1.0e+01, 1.0e-02],
       [1.5e+01, 0.0e+00, 1.0e-02],
       [5.0e+00, 2.0e+00, 5.0e+00],
       [1.5e+01, 0.0e+00, 1.0e-02],
       [0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 1.0e-02]], dtype=float32)

In [15]:
example_mesh.v1

array([[5.0e+00, 3.0e+00, 5.0e+00],
       [0.0e+00, 1.0e+01, 1.0e-02],
       [1.5e+01, 1.0e+01, 0.0e+00],
       [5.0e+00, 2.0e+00, 5.0e+00],
       [0.0e+00, 1.0e+01, 1.0e-02],
       [0.0e+00, 1.0e+01, 1.0e-02],
       [1.5e+01, 1.0e+01, 0.0e+00],
       [1.5e+01, 1.0e+01, 0.0e+00],
       [5.0e+00, 3.0e+00, 5.0e+00],
       [5.0e+00, 2.0e+00, 5.0e+00],
       [0.0e+00, 1.0e+01, 1.0e-02],
       [0.0e+00, 1.0e+01, 1.0e-02],
       [0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 1.0e+01, 1.0e-02],
       [1.5e+01, 1.0e+01, 0.0e+00],
       [5.0e+00, 3.0e+00, 5.0e+00],
       [5.0e+00, 3.0e+00, 5.0e+00],
       [0.0e+00, 1.0e+01, 1.0e-02],
       [0.0e+00, 1.0e+01, 1.0e-02]], dtype=float32)

In [16]:
example_mesh.v2

array([[3.0e+00, 3.0e+00, 5.0e+00],
       [1.5e+01, 1.0e+01, 0.0e+00],
       [1.5e+01, 0.0e+00, 1.0e-02],
       [0.0e+00, 0.0e+00, 1.0e-02],
       [1.5e+01, 1.0e+01, 1.0e-02],
       [3.0e+00, 3.0e+00, 5.0e+00],
       [1.5e+01, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00],
       [1.5e+01, 0.0e+00, 1.0e-02],
       [3.0e+00, 2.0e+00, 5.0e+00],
       [0.0e+00, 0.0e+00, 1.0e-02],
       [3.0e+00, 2.0e+00, 5.0e+00],
       [1.5e+01, 0.0e+00, 0.0e+00],
       [1.5e+01, 0.0e+00, 1.0e-02],
       [5.0e+00, 3.0e+00, 5.0e+00],
       [1.5e+01, 1.0e+01, 1.0e-02],
       [3.0e+00, 2.0e+00, 5.0e+00],
       [5.0e+00, 2.0e+00, 5.0e+00],
       [0.0e+00, 1.0e+01, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00]], dtype=float32)

In [18]:
example_mesh.x.flatten()

array([ 3.,  5.,  3.,  0.,  0., 15., 15., 15., 15., 15.,  5.,  0., 15.,
        0., 15.,  5.,  0.,  3.,  0., 15., 15.,  0., 15.,  0., 15.,  5.,
       15.,  0.,  5.,  3.,  3.,  0.,  0.,  3.,  0.,  3., 15.,  0., 15.,
        0.,  0., 15., 15.,  0.,  5., 15., 15., 15.,  5.,  5.,  3., 15.,
        5.,  5.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [20]:
example_mesh.min_

array([0., 0., 0.], dtype=float32)

In [21]:
example_mesh.max_

array([15., 10.,  5.], dtype=float32)

In [23]:
figure = plt.figure()
# axes = mplot3d.Axes3D(figure)
ax = figure.add_subplot(111, projection="3d")

ax.plot_trisurf(example_mesh.x.flatten(), example_mesh.y.flatten(), example_mesh.z.flatten());

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [9]:
help(example_mesh)

Help on Mesh in module stl.mesh object:

class Mesh(stl.stl.BaseStl)
 |  Mesh(*args, **kwargs)
 |  
 |  Mesh object with easy access to the vectors through v0, v1 and v2.
 |  The normals, areas, min, max and units are calculated automatically.
 |  
 |  :param numpy.array data: The data for this mesh
 |  :param bool calculate_normals: Whether to calculate the normals
 |  :param bool remove_empty_areas: Whether to remove triangles with 0 area
 |          (due to rounding errors for example)
 |  
 |  :ivar str name: Name of the solid, only exists in ASCII files
 |  :ivar numpy.array data: Data as :func:`BaseMesh.dtype`
 |  :ivar numpy.array points: All points (Nx9)
 |  :ivar numpy.array normals: Normals for this mesh, calculated automatically
 |      by default (Nx3)
 |  :ivar numpy.array vectors: Vectors in the mesh (Nx3x3)
 |  :ivar numpy.array attr: Attributes per vector (used by binary STL)
 |  :ivar numpy.array x: Points on the X axis by vertex (Nx3)
 |  :ivar numpy.array y: Points o