# Purpose

Understand the triangular mesh in an STL file as represented by the `numpy-stl` package, which is installed in your python installation with `pip install numpy-stl`.

# Imports

In [1]:
from pathlib import Path

import numpy as np
from stl import mesh

from mpl_toolkits import mplot3d
from matplotlib import pyplot as plt
%matplotlib widget


# Load example STL file

The example file was made with the following OpenSCAD code:

    pedestal = [15, 10, 2];
    top_thickness = 0.01;
    top = [2, 1, top_thickness];

    pyramid_height = 5;
    shift_top_x = 3;
    shift_top_y = 2;

    hull() {
        cube(pedestal);
        translate([shift_top_x, 
                   shift_top_y, 
                   pyramid_height - top_thickness
                  ]) cube(top);
    }

In [2]:
stl_file = Path('.').resolve().parent / 'example-pyramid.stl'
stl_file

PosixPath('/Users/nordin/Documents/Projects/3D_printer_slicers/OpenGL-STL-slicer/example-pyramid.stl')

In [3]:
example_mesh = mesh.Mesh.from_file(stl_file)
example_mesh

# Explore mesh object

## Using `help()`

In [4]:
help(example_mesh)

Help on Mesh in module stl.mesh object:

class Mesh(stl.stl.BaseStl)
 |  Mesh(*args, **kwargs)
 |  
 |  Mesh object with easy access to the vectors through v0, v1 and v2.
 |  The normals, areas, min, max and units are calculated automatically.
 |  
 |  :param numpy.array data: The data for this mesh
 |  :param bool calculate_normals: Whether to calculate the normals
 |  :param bool remove_empty_areas: Whether to remove triangles with 0 area
 |          (due to rounding errors for example)
 |  
 |  :ivar str name: Name of the solid, only exists in ASCII files
 |  :ivar numpy.array data: Data as :func:`BaseMesh.dtype`
 |  :ivar numpy.array points: All points (Nx9)
 |  :ivar numpy.array normals: Normals for this mesh, calculated automatically
 |      by default (Nx3)
 |  :ivar numpy.array vectors: Vectors in the mesh (Nx3x3)
 |  :ivar numpy.array attr: Attributes per vector (used by binary STL)
 |  :ivar numpy.array x: Points on the X axis by vertex (Nx3)
 |  :ivar numpy.array y: Points o

## Points

Given N triangles, the `points` matrix has N rows. There are 9 values in each row. The first 3 values are the first triangle vertex, the second 3 are the second triangle vertex, and the last 3 are the third triangle vertex. The 3 values for each vertex represent its x,y,z coordinate. These vertices are generally called vectors.

In [5]:
len(example_mesh.points)

20

In [6]:
example_mesh.points

array([[ 3.,  2.,  5.,  5.,  3.,  5.,  3.,  3.,  5.],
       [ 0., 10.,  2.,  0.,  0.,  0.,  0.,  0.,  2.],
       [15.,  0.,  0., 15., 10.,  0., 15.,  0.,  2.],
       [15.,  0.,  2.,  5.,  2.,  5.,  0.,  0.,  2.],
       [15., 10.,  2.,  5.,  3.,  5., 15.,  0.,  2.],
       [ 3.,  2.,  5.,  3.,  3.,  5.,  0.,  0.,  2.],
       [ 0.,  0.,  0., 15., 10.,  0., 15.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.,  0.,  0., 10.,  2.],
       [ 3.,  3.,  5.,  5.,  3.,  5.,  0., 10.,  2.],
       [ 0.,  0.,  2.,  5.,  2.,  5.,  3.,  2.,  5.],
       [ 0., 10.,  2., 15., 10.,  0.,  0., 10.,  0.],
       [ 0., 10.,  0., 15., 10.,  0.,  0.,  0.,  0.],
       [15.,  0.,  2.,  0.,  0.,  0., 15.,  0.,  0.],
       [ 0.,  0.,  2.,  0.,  0.,  0., 15.,  0.,  2.],
       [15., 10.,  2., 15., 10.,  0.,  0., 10.,  2.],
       [15.,  0.,  2., 15., 10.,  0., 15., 10.,  2.],
       [ 0., 10.,  2.,  5.,  3.,  5., 15., 10.,  2.],
       [ 0.,  0.,  2.,  3.,  3.,  5.,  0., 10.,  2.],
       [ 5.,  2.,  5.,  5., 

## Vectors

Given N triangles, the `vectors` matrix has N rows. Every row has 3 vectors, which are the 3 vertices for that triangle.

In [7]:
len(example_mesh.vectors)

20

In [8]:
example_mesh.vectors

array([[[ 3.,  2.,  5.],
        [ 5.,  3.,  5.],
        [ 3.,  3.,  5.]],

       [[ 0., 10.,  2.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  2.]],

       [[15.,  0.,  0.],
        [15., 10.,  0.],
        [15.,  0.,  2.]],

       [[15.,  0.,  2.],
        [ 5.,  2.,  5.],
        [ 0.,  0.,  2.]],

       [[15., 10.,  2.],
        [ 5.,  3.,  5.],
        [15.,  0.,  2.]],

       [[ 3.,  2.,  5.],
        [ 3.,  3.,  5.],
        [ 0.,  0.,  2.]],

       [[ 0.,  0.,  0.],
        [15., 10.,  0.],
        [15.,  0.,  0.]],

       [[ 0., 10.,  0.],
        [ 0.,  0.,  0.],
        [ 0., 10.,  2.]],

       [[ 3.,  3.,  5.],
        [ 5.,  3.,  5.],
        [ 0., 10.,  2.]],

       [[ 0.,  0.,  2.],
        [ 5.,  2.,  5.],
        [ 3.,  2.,  5.]],

       [[ 0., 10.,  2.],
        [15., 10.,  0.],
        [ 0., 10.,  0.]],

       [[ 0., 10.,  0.],
        [15., 10.,  0.],
        [ 0.,  0.,  0.]],

       [[15.,  0.,  2.],
        [ 0.,  0.,  0.],
        [15.,  0.,  0.]],


## v0, v1, v2

Given N triangles, each array, `v0, v0, v2` has N elements with each element being a vector (xyz values).

In [9]:
example_mesh.v0

array([[ 3.,  2.,  5.],
       [ 0., 10.,  2.],
       [15.,  0.,  0.],
       [15.,  0.,  2.],
       [15., 10.,  2.],
       [ 3.,  2.,  5.],
       [ 0.,  0.,  0.],
       [ 0., 10.,  0.],
       [ 3.,  3.,  5.],
       [ 0.,  0.,  2.],
       [ 0., 10.,  2.],
       [ 0., 10.,  0.],
       [15.,  0.,  2.],
       [ 0.,  0.,  2.],
       [15., 10.,  2.],
       [15.,  0.,  2.],
       [ 0., 10.,  2.],
       [ 0.,  0.,  2.],
       [ 5.,  2.,  5.],
       [15.,  0.,  2.]], dtype=float32)

In [10]:
example_mesh.v1

array([[ 5.,  3.,  5.],
       [ 0.,  0.,  0.],
       [15., 10.,  0.],
       [ 5.,  2.,  5.],
       [ 5.,  3.,  5.],
       [ 3.,  3.,  5.],
       [15., 10.,  0.],
       [ 0.,  0.,  0.],
       [ 5.,  3.,  5.],
       [ 5.,  2.,  5.],
       [15., 10.,  0.],
       [15., 10.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [15., 10.,  0.],
       [15., 10.,  0.],
       [ 5.,  3.,  5.],
       [ 3.,  3.,  5.],
       [ 5.,  3.,  5.],
       [ 5.,  3.,  5.]], dtype=float32)

In [11]:
example_mesh.v2

array([[ 3.,  3.,  5.],
       [ 0.,  0.,  2.],
       [15.,  0.,  2.],
       [ 0.,  0.,  2.],
       [15.,  0.,  2.],
       [ 0.,  0.,  2.],
       [15.,  0.,  0.],
       [ 0., 10.,  2.],
       [ 0., 10.,  2.],
       [ 3.,  2.,  5.],
       [ 0., 10.,  0.],
       [ 0.,  0.,  0.],
       [15.,  0.,  0.],
       [15.,  0.,  2.],
       [ 0., 10.,  2.],
       [15., 10.,  2.],
       [15., 10.,  2.],
       [ 0., 10.,  2.],
       [ 3.,  2.,  5.],
       [ 5.,  2.,  5.]], dtype=float32)

## x, y, z

Given N triangles, the arrays `x, y, z` each have N rows. Each row has the x values of the 3 vectors for that triangle (or the y values or the z values).

In [12]:
example_mesh.x

array([[ 3.,  5.,  3.],
       [ 0.,  0.,  0.],
       [15., 15., 15.],
       [15.,  5.,  0.],
       [15.,  5., 15.],
       [ 3.,  3.,  0.],
       [ 0., 15., 15.],
       [ 0.,  0.,  0.],
       [ 3.,  5.,  0.],
       [ 0.,  5.,  3.],
       [ 0., 15.,  0.],
       [ 0., 15.,  0.],
       [15.,  0., 15.],
       [ 0.,  0., 15.],
       [15., 15.,  0.],
       [15., 15., 15.],
       [ 0.,  5., 15.],
       [ 0.,  3.,  0.],
       [ 5.,  5.,  3.],
       [15.,  5.,  5.]], dtype=float32)

In [13]:
example_mesh.x.flatten()

array([ 3.,  5.,  3.,  0.,  0.,  0., 15., 15., 15., 15.,  5.,  0., 15.,
        5., 15.,  3.,  3.,  0.,  0., 15., 15.,  0.,  0.,  0.,  3.,  5.,
        0.,  0.,  5.,  3.,  0., 15.,  0.,  0., 15.,  0., 15.,  0., 15.,
        0.,  0., 15., 15., 15.,  0., 15., 15., 15.,  0.,  5., 15.,  0.,
        3.,  0.,  5.,  5.,  3., 15.,  5.,  5.], dtype=float32)

## min, max

Given N triangles, `min_` and `max_` are 3-element vectors that point to the minimum and maximum corners of the rectangular volume that fully contains all of the triangles. 

In [14]:
example_mesh.min_

array([0., 0., 0.], dtype=float32)

In [15]:
example_mesh.max_

array([15., 10.,  5.], dtype=float32)

# 3D plots

## plot_trisurf()

In [16]:
fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

ax.plot_trisurf(example_mesh.x.flatten(), example_mesh.y.flatten(), example_mesh.z.flatten()); #, cmap=plt.cm.CMRmap);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Note that this 3D plot is not accurate &rarr; where did the pedestal go?

## Plot mesh with edges colored

See Aguy's answer at [plot_trisurface with custom color array](https://stackoverflow.com/questions/63298864/plot-trisurface-with-custom-color-array).

In [17]:
fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

collection = mplot3d.art3d.Poly3DCollection(example_mesh.vectors, edgecolors='C3')
ax.add_collection(collection)

# Give auto_scale all of the x,y,z values and let it figure out axes limits
ax.auto_scale_xyz(example_mesh.x.flatten(), example_mesh.y.flatten(), example_mesh.z.flatten())

ax.set_xlabel('x (mm)')
ax.set_ylabel('y (mm)')
ax.set_zlabel('z (mm)')
ax.set_title('Example STL File Mesh');

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Color each triangle - doesn't work

From [mpl_toolkits.mplot3d.art3d.Poly3DCollection](https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.art3d.Poly3DCollection.html):

    set_facecolor(self, colors)
        Set the facecolor(s) of the collection. c can be a color (all patches have same color), or a sequence of colors; if it is a sequence the patches will cycle through the sequence.

        If c is 'none', the patch will not be filled.


In [18]:
some_colors = [
       (0.83106498, 0.23844675, 0.30880431, 1.        ),
       (0.99146482, 0.67735486, 0.37808535, 1.        ),
       (0.19946175, 0.5289504 , 0.73910035, 1.        ),
       (0.35509419, 0.32733564, 0.64359862, 1.        ),
       (0.36862745, 0.30980392, 0.63529412, 1.        )
]
some_colors

[(0.83106498, 0.23844675, 0.30880431, 1.0),
 (0.99146482, 0.67735486, 0.37808535, 1.0),
 (0.19946175, 0.5289504, 0.73910035, 1.0),
 (0.35509419, 0.32733564, 0.64359862, 1.0),
 (0.36862745, 0.30980392, 0.63529412, 1.0)]

In [19]:
fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

collection = mplot3d.art3d.Poly3DCollection(example_mesh.vectors, edgecolors='k')
collection.set_facecolor(some_colors)
ax.add_collection(collection)

# Give auto_scale all of the x,y,z values and let it figure out axes limits
ax.auto_scale_xyz(example_mesh.x.flatten(), example_mesh.y.flatten(), example_mesh.z.flatten())

ax.set_xlabel('x (mm)')
ax.set_ylabel('y (mm)')
ax.set_zlabel('z (mm)')
ax.set_title('Example STL File Mesh');

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …