In [1]:
from pathlib import Path

import numpy as np
from stl import mesh

from mpl_toolkits import mplot3d
from matplotlib import pyplot as plt
%matplotlib widget


mesh.Mesh.dtype

dtype([('normals', '<f4', (3,)), ('vectors', '<f4', (3, 3)), ('attr', '<u2', (1,))])

In [2]:
stl_file = Path('.').resolve().parent / 'example-pyramid.stl'
stl_file

PosixPath('/Users/nordin/Documents/Projects/3D_printer_slicers/OpenGL-STL-slicer/example-pyramid.stl')

In [3]:
example_mesh = mesh.Mesh.from_file(stl_file)
example_mesh

In [4]:
len(example_mesh.points)

20

In [5]:
example_mesh.points

array([[3.0e+00, 2.0e+00, 5.0e+00, 5.0e+00, 3.0e+00, 5.0e+00, 3.0e+00,
        3.0e+00, 5.0e+00],
       [0.0e+00, 1.0e+01, 0.0e+00, 0.0e+00, 1.0e+01, 1.0e-02, 1.5e+01,
        1.0e+01, 0.0e+00],
       [1.5e+01, 0.0e+00, 0.0e+00, 1.5e+01, 1.0e+01, 0.0e+00, 1.5e+01,
        0.0e+00, 1.0e-02],
       [1.5e+01, 0.0e+00, 1.0e-02, 5.0e+00, 2.0e+00, 5.0e+00, 0.0e+00,
        0.0e+00, 1.0e-02],
       [1.5e+01, 1.0e+01, 0.0e+00, 0.0e+00, 1.0e+01, 1.0e-02, 1.5e+01,
        1.0e+01, 1.0e-02],
       [5.0e+00, 3.0e+00, 5.0e+00, 0.0e+00, 1.0e+01, 1.0e-02, 3.0e+00,
        3.0e+00, 5.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 1.5e+01, 1.0e+01, 0.0e+00, 1.5e+01,
        0.0e+00, 0.0e+00],
       [0.0e+00, 1.0e+01, 0.0e+00, 1.5e+01, 1.0e+01, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [1.5e+01, 1.0e+01, 1.0e-02, 5.0e+00, 3.0e+00, 5.0e+00, 1.5e+01,
        0.0e+00, 1.0e-02],
       [0.0e+00, 0.0e+00, 1.0e-02, 5.0e+00, 2.0e+00, 5.0e+00, 3.0e+00,
        2.0e+00, 5.0e+00],
       [3.0e+00, 2.0

In [6]:
example_mesh.points[0]

array([3., 2., 5., 5., 3., 5., 3., 3., 5.], dtype=float32)

In [10]:
len(example_mesh.vectors)

20

In [9]:
example_mesh.vectors

array([[[3.0e+00, 2.0e+00, 5.0e+00],
        [5.0e+00, 3.0e+00, 5.0e+00],
        [3.0e+00, 3.0e+00, 5.0e+00]],

       [[0.0e+00, 1.0e+01, 0.0e+00],
        [0.0e+00, 1.0e+01, 1.0e-02],
        [1.5e+01, 1.0e+01, 0.0e+00]],

       [[1.5e+01, 0.0e+00, 0.0e+00],
        [1.5e+01, 1.0e+01, 0.0e+00],
        [1.5e+01, 0.0e+00, 1.0e-02]],

       [[1.5e+01, 0.0e+00, 1.0e-02],
        [5.0e+00, 2.0e+00, 5.0e+00],
        [0.0e+00, 0.0e+00, 1.0e-02]],

       [[1.5e+01, 1.0e+01, 0.0e+00],
        [0.0e+00, 1.0e+01, 1.0e-02],
        [1.5e+01, 1.0e+01, 1.0e-02]],

       [[5.0e+00, 3.0e+00, 5.0e+00],
        [0.0e+00, 1.0e+01, 1.0e-02],
        [3.0e+00, 3.0e+00, 5.0e+00]],

       [[0.0e+00, 0.0e+00, 0.0e+00],
        [1.5e+01, 1.0e+01, 0.0e+00],
        [1.5e+01, 0.0e+00, 0.0e+00]],

       [[0.0e+00, 1.0e+01, 0.0e+00],
        [1.5e+01, 1.0e+01, 0.0e+00],
        [0.0e+00, 0.0e+00, 0.0e+00]],

       [[1.5e+01, 1.0e+01, 1.0e-02],
        [5.0e+00, 3.0e+00, 5.0e+00],
        [1.5e+01, 0.0e

In [7]:
example_mesh.vectors[0]

array([[3., 2., 5.],
       [5., 3., 5.],
       [3., 3., 5.]], dtype=float32)

In [8]:
example_mesh.vectors[0][1]

array([5., 3., 5.], dtype=float32)

In [11]:
x_values = set()
y_values = set()
z_values = set()
for vectors in example_mesh.vectors:
    for vector in vectors:
        x_values.add(vector[0])
        y_values.add(vector[1])
        z_values.add(vector[2])
    # print(vectors)
print(x_values)
print(y_values)
print(z_values)

{0.0, 3.0, 5.0, 15.0}
{10.0, 0.0, 2.0, 3.0}
{0.0, 0.01, 5.0}


In [6]:
figure = plt.figure()
# axes = mplot3d.Axes3D(figure)
ax = figure.add_subplot(111, projection="3d")

# Add the vectors to the plot
ax.add_collection3d(mplot3d.art3d.Poly3DCollection(example_mesh.vectors))
# Auto scale to the mesh size
scale = example_mesh.points.flatten()
#ax.auto_scale_xyz(scale, scale, scale)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [9]:
help(example_mesh)

Help on Mesh in module stl.mesh object:

class Mesh(stl.stl.BaseStl)
 |  Mesh(*args, **kwargs)
 |  
 |  Mesh object with easy access to the vectors through v0, v1 and v2.
 |  The normals, areas, min, max and units are calculated automatically.
 |  
 |  :param numpy.array data: The data for this mesh
 |  :param bool calculate_normals: Whether to calculate the normals
 |  :param bool remove_empty_areas: Whether to remove triangles with 0 area
 |          (due to rounding errors for example)
 |  
 |  :ivar str name: Name of the solid, only exists in ASCII files
 |  :ivar numpy.array data: Data as :func:`BaseMesh.dtype`
 |  :ivar numpy.array points: All points (Nx9)
 |  :ivar numpy.array normals: Normals for this mesh, calculated automatically
 |      by default (Nx3)
 |  :ivar numpy.array vectors: Vectors in the mesh (Nx3x3)
 |  :ivar numpy.array attr: Attributes per vector (used by binary STL)
 |  :ivar numpy.array x: Points on the X axis by vertex (Nx3)
 |  :ivar numpy.array y: Points o